### PR TITLE
Move "copyImageBitmapToTexture" form "GPUCommandEncoder" to "GPUQueue"

### PR DESCRIPTION
**Pull request by shaoboyan**

### CODE REVIEW

**Comment by shaoboyan** [comment]
@austinEng  PTAL!

**Comment by austinEng** [comment]
LGTM

**Comment by shaoboyan** [comment]
@kainino0x updated the patch. Does this what your mean?

**Comment by kainino0x** [comment]
I'll publish a new version to npm tomorrow.

**Comment by kainino0x** [comment]
Done, 0.0.19.

**Pull request merged**
