### PR TITLE
Update gpuweb

### PR DESCRIPTION
**Pull request by vonture**
* Remove maxInterStageShaderComponents
 * Add GPUTextureViewDescriptor usage
 * Add featureLevel
 * Add sliced 3D texture formats
 * Support undefined limits
 * Update various documentation

### CODE REVIEW

**Comment by vonture** [comment]
I'm not sure why a bunch of documentation disappeared in the generated files. I left it in the dist file though.

**Review by toji — APPROVED** [review]
LGTM, thanks for the update!

**Comment by kainino0x** [comment]
> I'm not sure why a bunch of documentation disappeared in the generated files. I left it in the dist file though.

I'm guessing something changed about the HTML that bikeshed produces and now the script that scrapes it for documentation isn't finding it. Will have to look into that sometime....

**Comment by kainino0x** [comment]
published 0.1.46

**Pull request merged**
