### PR TITLE
Remove constants.ts

### PR DESCRIPTION
**Pull request by kainino0x**
This file was previously used to ease the use of string enums in
TypeScript projects. Since then, we found that `'string-enum' as const`
could be used instead. The WebGPU CTS stopped using this file a long
time ago and hasn't encountered issues with that choice.

### CODE REVIEW

**Comment by kainino0x** [comment]
fyi @Richard-Yunchao @sebavan @austinEng and I don't know who else might need to know about this.

**Comment by austinEng** [comment]
super, thanks for the heads up

**Comment by HypnosNova** [comment]
I think it would be better to remove "package-lock.json" or "yarn.lock" file since in different company or country, people have npm mirror or yarn mirror to help them download dependencies much faster. In that way, different developers might have totally different lock file.
lock file could be added into git ignore.

**Comment by kainino0x** [comment]
npm itself tells me to check this file in, though of course in this case it's pretty inconsequential. Still, it seems best to stick with the file layout that almost every project follows.
https://stackoverflow.com/a/44210813

**Pull request merged**
